export const REFRESH_QUESTION_ALL = "REFRESH_QUESTION_ALL";
export const FECTH_QUESTION_SUCCESS = "FECTH_QUESTION_SUCCESS";
export const FECTH_QUESTION_BY_INDEX = "FECTH_QUESTION_BY_INDEX";
export const FECTH_QUESTION_CURRENT = "FECTH_QUESTION_CURRENT";
export const REFESH_QUESTION_CURENT_INDEX = "REFESH_QUESTION_CURENT_INDEX";